name: sharebox
description: Private Windows + Android text/image transfer app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: 2.17.2
  file_picker: 13.1.0
  desktop_drop: 0.8.4
  shared_preferences: 2.5.5
  mime: 2.1.0
  uuid: 4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
